"""changing 'id' field names

Revision ID: 4786f3321c6c
Revises: af57f6f7089d
Create Date: 2025-09-12 12:59:58.429120

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel



# revision identifiers, used by Alembic.
revision: str = '4786f3321c6c'
down_revision: Union[str, Sequence[str], None] = 'af57f6f7089d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('chats', sa.Column('user_uid', sa.Uuid(), nullable=True))
    op.drop_constraint(op.f('chats_user_id_fkey'), 'chats', type_='foreignkey')
    op.create_foreign_key(None, 'chats', 'users', ['user_uid'], ['uuid'])
    op.drop_column('chats', 'user_id')
    op.add_column('questionsandanswers', sa.Column('chat_uid', sa.Uuid(), nullable=True))
    op.drop_constraint(op.f('questionsandanswers_chat_id_fkey'), 'questionsandanswers', type_='foreignkey')
    op.create_foreign_key(None, 'questionsandanswers', 'chats', ['chat_uid'], ['uuid'])
    op.drop_column('questionsandanswers', 'chat_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('questionsandanswers', sa.Column('chat_id', sa.UUID(), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'questionsandanswers', type_='foreignkey')
    op.create_foreign_key(op.f('questionsandanswers_chat_id_fkey'), 'questionsandanswers', 'chats', ['chat_id'], ['uuid'])
    op.drop_column('questionsandanswers', 'chat_uid')
    op.add_column('chats', sa.Column('user_id', sa.UUID(), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'chats', type_='foreignkey')
    op.create_foreign_key(op.f('chats_user_id_fkey'), 'chats', 'users', ['user_id'], ['uuid'])
    op.drop_column('chats', 'user_uid')
    # ### end Alembic commands ###
