"""new conversations memory table

Revision ID: 665c3d397e63
Revises: 712c0ac25c6e
Create Date: 2026-08-01 13:14:58.419611

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '665c3d397e63'
down_revision: Union[str, Sequence[str], None] = '712c0ac25c6e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('conversation_summary',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('summary', sa.TEXT(), nullable=False),
    sa.Column('start_message', sa.UUID(), nullable=False),
    sa.Column('last_message', sa.UUID(), nullable=False),
    sa.Column('n_summarized', sa.INTEGER(), nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), nullable=False),
    sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['id'], ['chats.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['last_message'], ['messages.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['start_message'], ['messages.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('conversation_summary')
    # ### end Alembic commands ###
